//
//  YomiganaSampleTests.swift
//  YomiganaSampleTests
//
//  Created by Takenori Kabeya on 2024/12/21.
//

import XCTest
@testable import YomiganaSample

final class YomiganaSampleTests: XCTestCase {

    override func setUpWithError() throws {
        // Put setup code here. This method is called before the invocation of each test method in the class.
    }

    override func tearDownWithError() throws {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
    }

    func test_latinToHiragana() throws {
        XCTAssertEqual(YomiganaUtils.latinToHiragana("shīeichi"), "しーえいち")
        XCTAssertEqual(YomiganaUtils.latinToHiragana("pettobotorurakku H16cmD22senchimētoru"), "ぺっとぼとるらっく H16cmD22せんちめーとる")
        XCTAssertEqual(YomiganaUtils.latinToHiragana("shin'yokohama"), "しんよこはま")
    }
    
    func test_getYomiganaOf_NN() throws {
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("新横浜"), "しんよこはま")
    }
    
    func test_getYomiganaOf_LatinAndHiragana() throws {
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ペットボトルラックes"), "ぺっとぼとるらっくes")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("dentalyo"), "dentalyo")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("dentalよ"), "dentalよ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ｄｅｎｔａｌｙｏ"), "dentalyo")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ｄｅｎｔａｌよ"), "dentalよ")
    }
    
    func test_getYomiganaOf_Katakana() throws {
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("カ"), "か")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ヵ"), "ゕ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("エアーサロンパス １ｃｍ"),"えあーさろんぱす 1せんちめーとる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf(" ナ"), " な")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf(" "), "")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf(""), "")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ア〜モンド"), "あ〜もんど") // 波ダッシュは波ダッシュのまま
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("マジで！？"), "まじで!?") // 記号類は半角になる
    }
    
    func test_getYomiganaOf_FoundNGCase() throws {
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("散"), "さん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("苓"), "") // ほんとは「れい」だけどiOSは読めない
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("五苓散"), "いつさん") // ほんとは「ごれいさん」だけどiOSは読めない
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("五苓散錠剤"), "いつさんじょうざい")
    }
    
    func test_getYomiganaOf_AllLatin() throws {
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("vox amplug2 bass"), "vox amplug2 bass")
    }
    
    func test_getYomiganaOf_NonKanji() throws {
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ちっちぇー"),"ちっちぇー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ちっちゃー"),"ちっちゃー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ちっちょーりーな"),"ちっちょーりーな")
        
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("チッチェー"),"ちっちぇー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("チッチャー"),"ちっちゃー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("チッチョーリーナ"),"ちっちょーりーな")
        
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ティケッツ"),"てぃけっつ")
        
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ヴェロシティー"),"ゔぇろしてぃー")
        
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("フィナンシャル"),"ふぃなんしゃる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("エアーサロンパスＥＸ"),"えあーさろんぱすいーえっくす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("エアーサロンパスｅｘ"),"えあーさろんぱすex")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("エアーサロンパス １ｃｍ"),"えあーさろんぱす 1せんちめーとる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("エアーサロンパス ｃｍ"),"えあーさろんぱす cm")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("エアーサロンパス ＣＭ"),"えあーさろんぱす しーえむ")
        
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("エアーサロンパスEX"),"えあーさろんぱすいーえっくす")
        
    }
    
    func test_getYomiganaOf() throws {
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("アーモンド"),"あーもんど")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("あおさ"),"あおさ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("青唐辛子"),"あおとうがらし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("青ねぎ"),"あおねぎ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("青のり"),"あおのり")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("あおりいか"),"あおりいか")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("赤玉ねぎ"),"あかたまねぎ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("赤とうがらし"),"あかとうがらし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("赤ワイン"),"あかわいん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("揚げ油"),"あげあぶら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("あさり"),"あさり")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("あじ"),"あじ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("小豆"),"あずき")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("アスパラガス"),"あすぱらがす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("厚揚げ"),"あつあげ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("あなご"),"あなご")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("油揚げ"),"あぶらあげ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("アボカド"),"あぼかど")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("甘えび"),"あまえび")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("アルミホイル"),"あるみほいる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("あわび"),"あわび")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("アンチョビ"),"あんちょび")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("いか"),"いか")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("いくら"),"いくら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("イタリアンハーブミックス"),"いたりあんはーぶみっくす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("いちご"),"いちご")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("一味唐辛子"),"いちみとうがらし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("いなだ"),"いなだ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("衣料用柔軟剤"),"いりょうようじゅうなんざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("衣料用消臭剤"),"いりょうようしょうしゅうざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("衣料用洗剤"),"いりょうようせんざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("衣料用漂白剤"),"いりょうようひょうはくざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("いわし"),"いわし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("いわし缶"),"いわしかん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("いんげん豆"),"いんげんまめ")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("五香粉"),"うーしゃーふぇん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ウスターソース"),"うすたーそーす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("うずら玉子"),"うずらたまご")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("うどん乾麺"),"うどんかんめん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("うどん生麺"),"うどんなまめん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("うなぎ"),"うなぎ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("うに"),"うに")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("梅干し"),"うめぼし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("エストラゴン"),"えすとらごん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("枝豆"),"えだまめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("えのき茸"),"えのきたけ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("えび"),"えび")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("エリンギ"),"えりんぎ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("えんどう豆"),"えんどうまめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("オイスターソース"),"おいすたーそーす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("オイルサーディン"),"おいるさーでぃん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("大葉"),"おおば")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("オールスパイス"),"おーるすぱいす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("オクラ"),"おくら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("お好み焼きソース"),"おこのみやきそーす")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("おしゃれ着用洗剤"),"おしゃれぎようせんざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("オニオンパウダー"),"おにおんぱうだー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("オリーブオイル"),"おりーぶおいる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("オレガノ"),"おれがの")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("カー"),"かー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("貝割れ大根"),"かいわれだいこん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("牡蠣"),"かき")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("柿"),"かき")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("牡蠣缶"),"かきかん")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("角砂糖"),"かくざとう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("かじき"),"かじき")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("片栗粉"),"かたくりこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("かつお"),"かつお")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("かつお節"),"かつおぶし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("カットトマト缶"),"かっととまとかん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("かに"),"かに")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("かに缶"),"かにかん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("かぶ"),"かぶ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("かぼす"),"かぼす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("かぼちゃ"),"かぼちゃ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("かまぼこ"),"かまぼこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("カマンベールチーズ"),"かまんべーるちーず")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("からし"),"からし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("からしチューブ"),"からしちゅーぶ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("辛子明太子"),"からしめんたいこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ガラムマサラ"),"がらむまさら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("カリフラワー"),"かりふらわー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("カルダモン"),"かるだもん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("かれい"),"かれい")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("カレー粉"),"かれーこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("カレールー"),"かれーるー")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("乾電池単1"),"かんでんちたんいち")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("乾電池単3"),"かんでんちたんさん")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("乾電池単2"),"かんでんちたんに")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("乾電池単4"),"かんでんちたんよん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("かんぴょう"),"かんぴょう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("きくらげ"),"きくらげ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("きす"),"きす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("キッチンペーパー"),"きっちんぺーぱー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("絹さや"),"きぬさや")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("木の芽"),"きのめ")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("キャノーラ油"),"きゃのーらゆ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("キャベツ"),"きゃべつ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("キャラウェイ"),"きゃらうぇい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛肩（薄切り）"),"ぎゅうかた(うすぎり)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛肩ロース（薄切り）"),"ぎゅうかたろーす(うすぎり)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛肩ロース（ブロック）"),"ぎゅうかたろーす(ぶろっく)")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛カルビ"),"ぎゅうかるび")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛切り落とし"),"ぎゅうきりおとし")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛こま切れ"),"ぎゅうこまぎれ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛タン"),"ぎゅうたん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛乳"),"ぎゅうにゅう")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛ハチノス"),"ぎゅうはちのす")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛ひき肉"),"ぎゅうひきにく")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛豚合いびき肉"),"ぎゅうぶたあいびきにく")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛ホルモン"),"ぎゅうほるもん")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛もも（薄切り）"),"ぎゅうもも（うすぎり）")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("きゅうり"),"きゅうり")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛レバー"),"ぎゅうればー")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("牛ロース（薄切り）"),"ぎゅうろーす（うすぎり）")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("餃子の皮"),"ぎょうざのかわ")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("強力粉"),"きょうりきこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("切り干し大根"),"きりぼしだいこん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("金時豆"),"きんときまめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ぎんなん"),"ぎんなん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("葛きり"),"くずきり")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("クッキングシート"),"くっきんぐしーと")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("クッキングペーパー"),"くっきんぐぺーぱー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("グリーンピース"),"ぐりーんぴーす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("くるまえび"),"くるまえび")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("グレープシードオイル"),"ぐれーぷしーどおいる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("クレソン"),"くれそん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("黒こしょう"),"くろこしょう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("黒豆"),"くろまめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ケチャップ"),"けちゃっぷ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("剣先いか"),"けんさきいか")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("甲いか"),"こういか")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ゴーヤ"),"ごーや")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("黒糖"),"こくとう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("こしょう"),"こしょう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("粉チーズ"),"こなちーず")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ごぼう"),"ごぼう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ごま"),"ごま")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("ごま油"),"ごまあぶら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("小松菜"),"こまつな")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("ゴミ袋（20L）"),"ごみぶくろ（20りっとる）")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("ゴミ袋（30L）"),"ごみぶくろ（30りっとる）")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("ゴミ袋（45L）"),"ごみぶくろ（45りっとる）")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("ゴミ袋（70L）"),"ごみぶくろ（70りっとる）")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("小麦粉"),"こむぎこ")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("小麦全粒粉"),"こむぎぜんりゅうふん")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("米"),"こめ")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("米油"),"こめあぶら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("米酢"),"こめず")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("コリアンダー"),"こりあんだー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("コリアンダーシード"),"こりあんだーしーど")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ゴルゴンゾーラチーズ"),"ごるごんぞーらちーず")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("コンソメ"),"こんそめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("コンディショナー"),"こんでぃしょなー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("コンデンスミルク"),"こんでんすみるく")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("こんにゃく"),"こんにゃく")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("コンビーフ"),"こんびーふ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("昆布"),"こんぶ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ザーサイ"),"ざーさい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("サーモン"),"さーもん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("鮭"),"さけ")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("日本酒"),"にほんしゅ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("酒（料理用）"),"さけ(りょうりよう)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("鮭フレーク"),"さけふれーく")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("さざえ"),"さざえ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("笹かまぼこ"),"ささかまぼこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("殺虫スプレー"),"さっちゅうすぷれー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("さつま揚げ"),"さつまあげ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("さつまいも"),"さつまいも")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("里いも"),"さといも")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("砂糖"),"さとう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("サニーレタス"),"さにーれたす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("さば"),"さば")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("さば缶"),"さばかん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("サフラン"),"さふらん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("さやいんげん"),"さやいんげん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("さやえんどう"),"さやえんどう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("サラダ油"),"さらだあぶら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("さわら"),"さわら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("三角コーナー用ネット"),"さんかくこーなーようねっと")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("山椒"),"さんしょう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("さんま"),"さんま")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("しいたけ"),"しいたけ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("シーチキン"),"しーちきん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("塩"),"しお")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("塩昆布"),"しおこんぶ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("塩鮭"),"しおざけ")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("歯間ブラシ"),"しかんぶらし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ししとう"),"ししとう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("しじみ"),"しじみ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("七味唐辛子"),"しちみとうがらし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("シナモン"),"しなもん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("しめじ"),"しめじ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("じゃがいも"),"じゃがいも")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("シャンツァイ"),"しゃんつぁい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("シャンプー"),"しゃんぷー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("住居用カビ取り剤"),"じゅうきょようかびとりざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("住居用消臭剤"),"じゅうきょようしょうしゅうざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("住居用洗剤"),"じゅうきょようせんざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("住居用防虫剤"),"じゅうきょようぼうちゅうざい")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("焼売の皮"),"しゅうまいのかわ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("春菊"),"しゅんぎく")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("しょうが"),"しょうが")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("しょうがチューブ"),"しょうがちゅーぶ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("上新粉"),"じょうしんこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("しょうゆ"),"しょうゆ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("食洗機用洗剤"),"しょくせんきようせんざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("しらたき"),"しらたき")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("白玉粉"),"しらたまこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("白こしょう"),"しろこしょう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("白ワイン"),"しろわいん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("新じゃがいも"),"しんじゃがいも")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("新しょうが"),"しんしょうが")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("新玉ねぎ"),"しんたまねぎ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("酢"),"す")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("スイートチリソース"),"すいーとちりそーす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("すいか"),"すいか")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("すだち"),"すだち")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ズッキーニ"),"ずっきーに")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("スナックえんどう"),"すなっくえんどう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("スナップえんどう"),"すなっぷえんどう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("スパゲティ（乾麺）"),"すぱげてぃ(かんめん)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("スペアミント"),"すぺあみんと")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("スモークサーモン"),"すもーくさーもん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("スライスチーズ"),"すらいすちーず")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("スライスべーコン"),"すらいすべーこん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("すりごま"),"すりごま")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("するめいか"),"するめいか")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("セージ"),"せーじ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ゼラチン"),"ぜらちん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("セロリ"),"せろり")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("洗濯機用カビ取り剤"),"せんたくきようかびとりざい")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("洗面所用ハンドソープ"),"せんめんじょようはんどそーぷ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("そうめん乾麺"),"そうめんかんめん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ソーセージ"),"そーせーじ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("そでいか"),"そでいか")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("そば乾麺"),"そばかんめん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("そば生麺"),"そばなまめん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("そら豆"),"そらまめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ターメリック"),"たーめりっく")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("たい"),"たい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("大根"),"だいこん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("大豆"),"だいず")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("台所用クレンザー"),"だいどころようくれんざー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("台所用スポンジ"),"だいどころようすぽんじ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("台所用洗剤"),"だいどころようせんざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("台所用たわし"),"だいどころようたわし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("台所用ハンドソープ"),"だいどころようはんどそーぷ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("台所用漂白剤"),"だいどころようひょうはくざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("タイム"),"たいむ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("たけのこ"),"たけのこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("たこ"),"たこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("たこ焼きソース"),"たこやきそーす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("玉子"),"たまご")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("卵"),"たまご")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("たまねぎ"),"たまねぎ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("たら"),"たら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("タルタルソース"),"たるたるそーす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("タンス用防虫剤"),"たんすようぼうちゅうざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("チーズ"),"ちーず")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ちくわ"),"ちくわ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("焼豚"),"ちゃーしゅー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("中華麺（生麺）"),"ちゅうかめん(なまめん)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("中濃ソース"),"ちゅうのうそーす")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("中力粉"),"ちゅうりきこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("チリソース"),"ちりそーす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ちりめんじゃこ"),"ちりめんじゃこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ちんげんさい"),"ちんげんさい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("つぶ貝"),"つぶがい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ティッシュペーパー"),"てぃっしゅぺーぱー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ディル"),"でぃる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("デミグラスソース缶"),"でみぐらすそーすかん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("天かす"),"てんかす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("甜麺醤"),"てんめんじゃん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("トイレットペーパー"),"といれっとぺーぱー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("トイレ用消臭剤"),"といれようしょうしゅうざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("トイレ用洗剤"),"といれようせんざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("とうがらし"),"とうがらし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("とうがん"),"とうがん")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("豆豉醤"),"とうちーじゃん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豆乳"),"とうにゅう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豆板醤"),"とうばんじゃん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豆腐"),"とうふ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豆苗"),"とうみょう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("とうもろこし"),"とうもろこし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("トマト"),"とまと")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("トマトケチャップ"),"とまとけちゃっぷ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ドライイースト"),"どらいいーすと")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("とり貝"),"とりがい")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("鶏ガラスープの素"),"とりがらすーぷのもと")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("鶏ささみ"),"とりささみ")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("鶏砂肝"),"とりすなぎも")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("鶏なんこつ"),"とりなんこつ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("鶏むね"),"とりむね")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("鶏もも"),"とりもも")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("鶏レバー"),"とりればー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("とんかつソース"),"とんかつそーす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("長いも"),"ながいも")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("長ねぎ"),"ながねぎ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("梨"),"なし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("なす"),"なす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("菜種油"),"なたねあぶら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("納豆"),"なっとう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("なつみかん"),"なつみかん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ナツメグ"),"なつめぐ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("菜の花"),"なのはな")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("バナメイえび"),"ばなめいえび")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("生クリーム"),"なまくりーむ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("なめこ"),"なめこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ナンプラー"),"なんぷらー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("煮干し"),"にぼし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("入浴剤"),"にゅうよくざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ニョクマム"),"にょくまむ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("にら"),"にら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("にんじん"),"にんじん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("にんにく"),"にんにく")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("にんにくチューブ"),"にんにくちゅーぶ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("にんにくパウダー"),"にんにくぱうだー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ねぎ"),"ねぎ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("海苔"),"のり")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("白菜"),"はくさい")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("薄力粉"),"はくりきこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("バジル"),"ばじる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("バジルパウダー"),"ばじるぱうだー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("パセリ"),"ぱせり")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("パセリパウダー"),"ぱせりぱうだー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("バター"),"ばたー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("はちみつ"),"はちみつ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("歯ブラシ"),"はぶらし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("パプリカ"),"ぱぷりか")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("パプリカパウダー"),"ぱぷりかぱうだー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("はまぐり"),"はまぐり")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("歯みがき"),"はみがき")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ハム"),"はむ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("バルサミコ酢"),"ばるさみこす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("はるさめ"),"はるさめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("春巻きの皮"),"はるまきのかわ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("パルメザンチーズ"),"ぱるめざんちーず")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("パン"),"ぱん")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("パン粉"),"ぱんこ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("はんぺん"),"はんぺん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ピーマン"),"ぴーまん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ビール"),"びーる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ピザソース"),"ぴざそーす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ピザチーズ"),"ぴざちーず")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("ひまわり油"),"ひまわりゆ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷やし中華麺"),"ひやしちゅうかめん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ひやむぎ乾麺"),"ひやむぎかんめん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ひよこ豆"),"ひよこまめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("麩"),"ふ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ブイヨン"),"ぶいよん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("フェンネル"),"ふぇんねる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ふき"),"ふき")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚肩（薄切り）"),"ぶたかた(うすぎり)")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚肩ロース（ブロック）"),"ぶたかたろーす(ぶろっく)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚切り落とし"),"ぶたきりおとし")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚こま切れ"),"ぶたこまぎれ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚タン"),"ぶたたん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚バラ（薄切り）"),"ぶたばら(うすぎり)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚バラ（ブロック）"),"ぶたばら(ぶろっく)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚ひき肉"),"ぶたひきにく")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚もも（薄切り）"),"ぶたもも(うすぎり)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚レバー"),"ぶたればー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚ロース（厚切り）"),"ぶたろーす(あつぎり)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("豚ロース（薄切り）"),"ぶたろーす(うすぎり)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ぶどう"),"ぶどう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ぶなしめじ"),"ぶなしめじ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ブラックタイガー"),"ぶらっくたいがー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ぶり"),"ぶり")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("フリーザーバッグ"),"ふりーざーばっぐ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ブルーベリー"),"ぶるーべりー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("フロス"),"ふろす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ブロッコリー"),"ぶろっこりー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ベーキングパウダー"),"べーきんぐぱうだー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ベーコン"),"べーこん")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("紅しょうが"),"べにしょうが")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("紅花油"),"べにばなゆ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("防虫スプレー"),"ぼうちゅうすぷれー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ほうれん草"),"ほうれんそう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ホースラディッシュ"),"ほーすらでぃっしゅ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ホールトマト缶"),"ほーるとまとかん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("干ししいたけ"),"ほししいたけ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ほたて"),"ほたて")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ほたるいか"),"ほたるいか")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ぼたんえび"),"ぼたんえび")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("ほっき貝"),"ほっきがい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ホットケーキミックス"),"ほっとけーきみっくす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ボディソープ"),"ぼでぃそーぷ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ホワイトアスパラ"),"ほわいとあすぱら")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ホワイトソース缶"),"ほわいとそーすかん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ホワイトペッパー"),"ほわいとぺっぱー")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("花椒"),"ほわじゃん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("本しめじ"),"ほんしめじ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("マーガリン"),"まーがりん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("まいたけ"),"まいたけ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("マカロニ"),"まかろに")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("まぐろ"),"まぐろ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("マスタード"),"ますたーど")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("マジョラム"),"まじょらむ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("マッシュルーム"),"まっしゅるーむ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("マトン"),"まとん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("マヨネーズ"),"まよねーず")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("実山椒"),"みざんしょう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("水菜"),"みずな")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("みそ"),"みそ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ミックスビーンズ"),"みっくすびーんず")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("三つ葉"),"みつば")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ミニトマト"),"みにとまと")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("みょうが"),"みょうが")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("みりん"),"みりん")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("ムール貝"),"むーるがい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("芽キャベツ"),"めきゃべつ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("めばる"),"めばる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("めんつゆ"),"めんつゆ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("メンマ"),"めんま")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("もち米"),"もちごめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("モッツァレラチーズ"),"もっつぁれらちーず")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("モップ用ウェットシート"),"もっぷよううぇっとしーと")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("モップ用ドライシート"),"もっぷようどらいしーと")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("もやし"),"もやし")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("モロヘイヤ"),"もろへいや")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("焼きそば麺"),"やきそばめん")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("焼き豆腐"),"やきどうふ")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("焼き豚"),"やきぶた")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("山いも"),"やまいも")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("やりいか"),"やりいか")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ゆず"),"ゆず")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ゆずこしょう"),"ゆずこしょう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ヨーグルト"),"よーぐると")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ラード"),"らーど")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ラーメン（乾麺）"),"らーめん(かんめん)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ラーメン（生麺）"),"らーめん(なまめん)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ラー油"),"らーゆ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ライスペーパー"),"らいすぺーぱー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ライム"),"らいむ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ラップ"),"らっぷ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ラディッシュ"),"らでぃっしゅ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ラム"),"らむ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("料理酒"),"りょうりしゅ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("りんご酢"),"りんごす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷蔵庫用消臭剤"),"れいぞうこようしょうしゅうざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍いんげん"),"れいとういんげん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍うどん"),"れいとううどん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍えだまめ"),"れいとうえだまめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍お好み焼き"),"れいとうおこのみやき")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍唐揚げ"),"れいとうからあげ")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍餃子"),"れいとうぎょうざ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍グラタン"),"れいとうぐらたん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍ケーキ"),"れいとうけーき")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍ごぼう"),"れいとうごぼう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍コロッケ"),"れいとうころっけ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍里いも"),"れいとうさといも")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍シーフードミックス"),"れいとうしーふーどみっくす")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍焼売"),"れいとうしゅうまい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍スパゲティ"),"れいとうすぱげてぃ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍そば"),"れいとうそば")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍炊き込みご飯"),"れいとうたきこみごはん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍たこ焼き"),"れいとうたこやき")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍炒飯"),"れいとうちゃーはん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍ドリア"),"れいとうどりあ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍とんかつ"),"れいとうとんかつ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍パイシート"),"れいとうぱいしーと")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍春巻き"),"れいとうはるまき")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍ハンバーグ"),"れいとうはんばーぐ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍ピザ"),"れいとうぴざ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍ピラフ"),"れいとうぴらふ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍フライドポテト"),"れいとうふらいどぽてと")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍ブロッコリー"),"れいとうぶろっこりー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍ほうれん草"),"れいとうほうれんそう")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍焼きおにぎり"),"れいとうやきおにぎり")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍焼きそば"),"れいとうやきそば")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍ラーメン"),"れいとうらーめん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("レタス"),"れたす")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("レッドペッパー"),"れっどぺっぱー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("レモン"),"れもん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("レモングラス"),"れもんぐらす")
        //XCTAssertEqual(YomiganaUtils.getYomiganaOf("レモン汁"),"れもんじる")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("れんこん"),"れんこん")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("レンズ豆"),"れんずまめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("冷凍庫用消臭剤"),"れいとうこようしょうしゅうざい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ローズマリー"),"ろーずまりー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ローリエ"),"ろーりえ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ワインビネガー"),"わいんびねがー")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("わかさぎ"),"わかさぎ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("わかめ"),"わかめ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("わさび"),"わさび")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("わさびチューブ"),"わさびちゅーぶ")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("和風だしの素"),"わふうだしのもと")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("玄米茶（茶葉）"),"げんまいちゃ(ちゃば)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("緑茶（茶葉）"),"りょくちゃ(ちゃば)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("煎茶（茶葉）"),"せんちゃ(ちゃば)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("深蒸し茶（茶葉）"),"ふかむしちゃ(ちゃば)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ほうじ茶（茶葉）"),"ほうじちゃ(ちゃば)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ウーロン茶（茶葉）"),"うーろんちゃ(ちゃば)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("玄米茶（ペットボトル）"),"げんまいちゃ(ぺっとぼとる)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("緑茶（ペットボトル）"),"りょくちゃ(ぺっとぼとる)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ジャスミン茶（茶葉）"),"じゃすみんちゃ(ちゃば)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ジャスミン茶（ペットボトル）"),"じゃすみんちゃ(ぺっとぼとる)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ウーロン茶（ペットボトル）"),"うーろんちゃ(ぺっとぼとる)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("ほうじ茶（ペットボトル）"),"ほうじちゃ(ぺっとぼとる)")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("チューハイ"),"ちゅーはい")
        XCTAssertEqual(YomiganaUtils.getYomiganaOf("炭酸水"),"たんさんすい")
    }


}
